package com.store59.pay.mapper;

import java.util.List;

import com.store59.pay.model.PayDetail;

public interface PayDetailMapper {
	
	List<PayDetail> selectByTradeNo(String tradeNo);
	
	int updateByCheckingIdSelective(PayDetail record);
	
	int batchUpdateByCheckingId(List<PayDetail> list);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_detail
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_detail
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    int insert(PayDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_detail
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    int insertSelective(PayDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_detail
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    PayDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_detail
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    int updateByPrimaryKeySelective(PayDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_detail
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    int updateByPrimaryKey(PayDetail record);
    
    int batchInsert(List<PayDetail> list);
}