package com.store59.pay.model;

import java.math.BigDecimal;
import java.util.Date;

public class BatchWithrawInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.id
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.trade_no
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.total_amount
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.total_count
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private Integer totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.currency_code
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private String currencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.remark
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.create_time
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.update_time
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.state
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_withraw_info.batch_trans_no
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    private String batchTransNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.id
     *
     * @return the value of batch_withraw_info.id
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.id
     *
     * @param id the value for batch_withraw_info.id
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.trade_no
     *
     * @return the value of batch_withraw_info.trade_no
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.trade_no
     *
     * @param tradeNo the value for batch_withraw_info.trade_no
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.total_amount
     *
     * @return the value of batch_withraw_info.total_amount
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.total_amount
     *
     * @param totalAmount the value for batch_withraw_info.total_amount
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.total_count
     *
     * @return the value of batch_withraw_info.total_count
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.total_count
     *
     * @param totalCount the value for batch_withraw_info.total_count
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.currency_code
     *
     * @return the value of batch_withraw_info.currency_code
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.currency_code
     *
     * @param currencyCode the value for batch_withraw_info.currency_code
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.remark
     *
     * @return the value of batch_withraw_info.remark
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.remark
     *
     * @param remark the value for batch_withraw_info.remark
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.create_time
     *
     * @return the value of batch_withraw_info.create_time
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.create_time
     *
     * @param createTime the value for batch_withraw_info.create_time
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.update_time
     *
     * @return the value of batch_withraw_info.update_time
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.update_time
     *
     * @param updateTime the value for batch_withraw_info.update_time
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.state
     *
     * @return the value of batch_withraw_info.state
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.state
     *
     * @param state the value for batch_withraw_info.state
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_withraw_info.batch_trans_no
     *
     * @return the value of batch_withraw_info.batch_trans_no
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public String getBatchTransNo() {
        return batchTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_withraw_info.batch_trans_no
     *
     * @param batchTransNo the value for batch_withraw_info.batch_trans_no
     *
     * @mbggenerated Fri May 20 14:33:22 CST 2016
     */
    public void setBatchTransNo(String batchTransNo) {
        this.batchTransNo = batchTransNo == null ? null : batchTransNo.trim();
    }
}