package com.store59.pay.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.trade_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.type
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorNo;
    
    // 交易描述
    private String tradeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_open_bank_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorOpenBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.amount
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.checking_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String checkingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.open_bank_code
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String openBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_branch_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_cert_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_mobile
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.receivor_alipay_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String receivorAlipayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.remark
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.create_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.update_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.trade_status
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Integer tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.order_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.payer_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Integer payerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.payer_contact
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private String payerContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.refund_status
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Integer refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_detail.refund_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    private Date refundTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.id
     *
     * @return the value of pay_detail.id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.id
     *
     * @param id the value for pay_detail.id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.trade_no
     *
     * @return the value of pay_detail.trade_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.trade_no
     *
     * @param tradeNo the value for pay_detail.trade_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.type
     *
     * @return the value of pay_detail.type
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.type
     *
     * @param type the value for pay_detail.type
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_no
     *
     * @return the value of pay_detail.receivor_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorNo() {
        return receivorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_no
     *
     * @param receivorNo the value for pay_detail.receivor_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorNo(String receivorNo) {
        this.receivorNo = receivorNo == null ? null : receivorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_name
     *
     * @return the value of pay_detail.receivor_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorName() {
        return receivorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_name
     *
     * @param receivorName the value for pay_detail.receivor_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorName(String receivorName) {
        this.receivorName = receivorName == null ? null : receivorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_open_bank_name
     *
     * @return the value of pay_detail.receivor_open_bank_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorOpenBankName() {
        return receivorOpenBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_open_bank_name
     *
     * @param receivorOpenBankName the value for pay_detail.receivor_open_bank_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorOpenBankName(String receivorOpenBankName) {
        this.receivorOpenBankName = receivorOpenBankName == null ? null : receivorOpenBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.amount
     *
     * @return the value of pay_detail.amount
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.amount
     *
     * @param amount the value for pay_detail.amount
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.checking_id
     *
     * @return the value of pay_detail.checking_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getCheckingId() {
        return checkingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.checking_id
     *
     * @param checkingId the value for pay_detail.checking_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setCheckingId(String checkingId) {
        this.checkingId = checkingId == null ? null : checkingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.open_bank_code
     *
     * @return the value of pay_detail.open_bank_code
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getOpenBankCode() {
        return openBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.open_bank_code
     *
     * @param openBankCode the value for pay_detail.open_bank_code
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setOpenBankCode(String openBankCode) {
        this.openBankCode = openBankCode == null ? null : openBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_branch_name
     *
     * @return the value of pay_detail.receivor_branch_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorBranchName() {
        return receivorBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_branch_name
     *
     * @param receivorBranchName the value for pay_detail.receivor_branch_name
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorBranchName(String receivorBranchName) {
        this.receivorBranchName = receivorBranchName == null ? null : receivorBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_cert_no
     *
     * @return the value of pay_detail.receivor_cert_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorCertNo() {
        return receivorCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_cert_no
     *
     * @param receivorCertNo the value for pay_detail.receivor_cert_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorCertNo(String receivorCertNo) {
        this.receivorCertNo = receivorCertNo == null ? null : receivorCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_mobile
     *
     * @return the value of pay_detail.receivor_mobile
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorMobile() {
        return receivorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_mobile
     *
     * @param receivorMobile the value for pay_detail.receivor_mobile
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorMobile(String receivorMobile) {
        this.receivorMobile = receivorMobile == null ? null : receivorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.receivor_alipay_no
     *
     * @return the value of pay_detail.receivor_alipay_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getReceivorAlipayNo() {
        return receivorAlipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.receivor_alipay_no
     *
     * @param receivorAlipayNo the value for pay_detail.receivor_alipay_no
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setReceivorAlipayNo(String receivorAlipayNo) {
        this.receivorAlipayNo = receivorAlipayNo == null ? null : receivorAlipayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.remark
     *
     * @return the value of pay_detail.remark
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.remark
     *
     * @param remark the value for pay_detail.remark
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.create_time
     *
     * @return the value of pay_detail.create_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.create_time
     *
     * @param createTime the value for pay_detail.create_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.update_time
     *
     * @return the value of pay_detail.update_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.update_time
     *
     * @param updateTime the value for pay_detail.update_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.trade_status
     *
     * @return the value of pay_detail.trade_status
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.trade_status
     *
     * @param tradeStatus the value for pay_detail.trade_status
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.order_id
     *
     * @return the value of pay_detail.order_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.order_id
     *
     * @param orderId the value for pay_detail.order_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.payer_id
     *
     * @return the value of pay_detail.payer_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Integer getPayerId() {
        return payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.payer_id
     *
     * @param payerId the value for pay_detail.payer_id
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setPayerId(Integer payerId) {
        this.payerId = payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.payer_contact
     *
     * @return the value of pay_detail.payer_contact
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public String getPayerContact() {
        return payerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.payer_contact
     *
     * @param payerContact the value for pay_detail.payer_contact
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setPayerContact(String payerContact) {
        this.payerContact = payerContact == null ? null : payerContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.refund_status
     *
     * @return the value of pay_detail.refund_status
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Integer getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.refund_status
     *
     * @param refundStatus the value for pay_detail.refund_status
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_detail.refund_time
     *
     * @return the value of pay_detail.refund_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_detail.refund_time
     *
     * @param refundTime the value for pay_detail.refund_time
     *
     * @mbggenerated Mon May 16 18:37:36 CST 2016
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

	/**
	 * @return the tradeDesc
	 */
	public String getTradeDesc() {
		return tradeDesc;
	}

	/**
	 * @param tradeDesc the tradeDesc to set
	 */
	public void setTradeDesc(String tradeDesc) {
		this.tradeDesc = tradeDesc;
	}
}